import { sql } from "drizzle-orm";
import { customType } from "drizzle-orm/pg-core";
import {
  bigint,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import type { MutationBody, MutationKind } from "@pergola/shared";
import { user } from "./auth-schema.js";

export * from "./auth-schema.js";

const now = () =>
  timestamp("created_at", { withTimezone: true }).notNull().defaultNow();

/** Postgres full-text search vector. Drizzle has no built-in for it. */
const tsvector = customType<{ data: string; driverData: string }>({
  dataType: () => "tsvector",
});

export const board = pgTable("board", {
  id: uuid("id").primaryKey().defaultRandom(),
  title: text("title").notNull(),
  /** "public" serves a read-only snapshot to anyone with the link. */
  visibility: text("visibility").$type<"private" | "public">().notNull().default("private"),
  /**
   * Per-board monotonic mutation counter. Every write bumps it inside the same
   * transaction that applies the change, which is what gives clients a cursor to
   * sync from and what serialises concurrent writers to one board (and only to
   * that board — different boards never contend).
   */
  seq: bigint("seq", { mode: "number" }).notNull().default(0),
  /** Board-scoped card numbering, so cards can be named out loud: PRG-142. */
  cardSeq: integer("card_seq").notNull().default(0),
  createdAt: now(),
});

export const list = pgTable(
  "list",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    boardId: uuid("board_id")
      .notNull()
      .references(() => board.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    /** Fractional index. See packages/shared/src/order.ts. */
    position: text("position").notNull(),
    /** Null means unlimited. The column turns amber when cards exceed it. */
    wipLimit: integer("wip_limit"),
    createdAt: now(),
  },
  (t) => [index("list_board_pos_idx").on(t.boardId, t.position)],
);

export const card = pgTable(
  "card",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    boardId: uuid("board_id")
      .notNull()
      .references(() => board.id, { onDelete: "cascade" }),
    listId: uuid("list_id")
      .notNull()
      .references(() => list.id, { onDelete: "cascade" }),
    position: text("position").notNull(),
    number: integer("number").notNull(),
    title: text("title").notNull(),
    descMd: text("desc_md"),
    dueAt: timestamp("due_at", { withTimezone: true }),
    startAt: timestamp("start_at", { withTimezone: true }),
    /** Trello's card cover, reduced to what people actually use: a colour. */
    coverColor: text("cover_color"),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdAt: now(),
    /*
     * Generated by Postgres on write, so the index can never drift from the text
     * it indexes — no trigger to maintain, no reindex job to forget. Title
     * outranks description, which is why they carry different weights.
     */
    search: tsvector("search").generatedAlwaysAs(
      sql`setweight(to_tsvector('simple', coalesce(title, '')), 'A') || setweight(to_tsvector('simple', coalesce(desc_md, '')), 'B')`,
    ),
  },
  (t) => [
    // The board's hot path: "give me one list, in order".
    index("card_list_pos_idx").on(t.listId, t.position),
    uniqueIndex("card_board_number_uq").on(t.boardId, t.number),
    index("card_search_idx").using("gin", t.search),
  ],
);

/**
 * The mutation log — the whole synchronisation layer.
 *
 * Real-time sync, reconnect, undo, the activity feed, the audit trail and
 * offline replay are all reads of this one table. There is no second write path.
 */
export const mutation = pgTable(
  "mutation",
  {
    /** Client-generated. Doubles as the idempotency key for retries and replay. */
    id: uuid("id").primaryKey(),
    boardId: uuid("board_id")
      .notNull()
      .references(() => board.id, { onDelete: "cascade" }),
    seq: bigint("seq", { mode: "number" }).notNull(),
    // Null only for mutations written before accounts existed, and for anything
    // the system does on its own behalf.
    actorId: text("actor_id").references(() => user.id, { onDelete: "set null" }),
    kind: text("kind").$type<MutationKind>().notNull(),
    payload: jsonb("payload").$type<MutationBody>().notNull(),
    /** The mutation that undoes this one. null => not undoable. */
    inverse: jsonb("inverse").$type<MutationBody | null>(),
    /**
     * Set when an automation rule produced this, rather than a person acting
     * directly. Encoding it in actor_id instead would break its foreign key —
     * and this way the activity feed can name the rule that did it.
     */
    ruleId: uuid("rule_id"),
    createdAt: now(),
  },
  (t) => [
    uniqueIndex("mutation_board_seq_uq").on(t.boardId, t.seq),
    index("mutation_feed_idx").on(t.boardId, sql`created_at DESC`),
  ],
);

export type BoardRow = typeof board.$inferSelect;
export type ListRow = typeof list.$inferSelect;
export type CardRow = typeof card.$inferSelect;
export type MutationRow = typeof mutation.$inferSelect;


/* ---------------------------------------------------------------- M1 tables */

/**
 * Who can see and change a board.
 *
 * Deliberately board-level rather than a full organisation model: a self-hosted
 * team shares boards, not an org chart. Organisations can be layered on later
 * without moving anything here.
 */
export const boardMember = pgTable(
  "board_member",
  {
    boardId: uuid("board_id")
      .notNull()
      .references(() => board.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** admin edits the board itself, member edits cards, observer reads. */
    role: text("role").$type<"admin" | "member" | "observer">().notNull().default("member"),
    createdAt: now(),
  },
  (t) => [
    primaryKey({ columns: [t.boardId, t.userId] }),
    index("board_member_user_idx").on(t.userId),
  ],
);

export const label = pgTable(
  "label",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    boardId: uuid("board_id")
      .notNull()
      .references(() => board.id, { onDelete: "cascade" }),
    name: text("name").notNull().default(""),
    /** A token name from the palette, never a raw hex — see web/src/lib/labels.ts. */
    color: text("color").notNull(),
    position: text("position").notNull(),
  },
  (t) => [index("label_board_idx").on(t.boardId)],
);

export const cardLabel = pgTable(
  "card_label",
  {
    cardId: uuid("card_id")
      .notNull()
      .references(() => card.id, { onDelete: "cascade" }),
    labelId: uuid("label_id")
      .notNull()
      .references(() => label.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.cardId, t.labelId] })],
);

export const cardAssignee = pgTable(
  "card_assignee",
  {
    cardId: uuid("card_id")
      .notNull()
      .references(() => card.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.cardId, t.userId] })],
);

export const checklist = pgTable(
  "checklist",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    cardId: uuid("card_id")
      .notNull()
      .references(() => card.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    position: text("position").notNull(),
  },
  (t) => [index("checklist_card_idx").on(t.cardId)],
);

export const checklistItem = pgTable(
  "checklist_item",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    checklistId: uuid("checklist_id")
      .notNull()
      .references(() => checklist.id, { onDelete: "cascade" }),
    text: text("text").notNull(),
    done: boolean("done").notNull().default(false),
    dueAt: timestamp("due_at", { withTimezone: true }),
    assigneeId: text("assignee_id").references(() => user.id, { onDelete: "set null" }),
    position: text("position").notNull(),
  },
  (t) => [index("checklist_item_list_idx").on(t.checklistId, t.position)],
);

export const comment = pgTable(
  "comment",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    cardId: uuid("card_id")
      .notNull()
      .references(() => card.id, { onDelete: "cascade" }),
    authorId: text("author_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    body: text("body").notNull(),
    editedAt: timestamp("edited_at", { withTimezone: true }),
    createdAt: now(),
  },
  (t) => [index("comment_card_idx").on(t.cardId, t.createdAt)],
);

/**
 * Link attachments only for now. File uploads need a storage adapter (local
 * volume by default, S3-compatible for Supabase Storage) and that lands with the
 * rest of M1's file handling.
 */
export const attachment = pgTable(
  "attachment",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    cardId: uuid("card_id")
      .notNull()
      .references(() => card.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    name: text("name").notNull(),
    addedBy: text("added_by").references(() => user.id, { onDelete: "set null" }),
    createdAt: now(),
  },
  (t) => [index("attachment_card_idx").on(t.cardId)],
);

export type BoardMemberRow = typeof boardMember.$inferSelect;
export type LabelRow = typeof label.$inferSelect;
export type ChecklistRow = typeof checklist.$inferSelect;
export type ChecklistItemRow = typeof checklistItem.$inferSelect;
export type CommentRow = typeof comment.$inferSelect;
export type AttachmentRow = typeof attachment.$inferSelect;


/**
 * Custom fields.
 *
 * Board-scoped definitions, card-scoped values, and the value is always text —
 * the field's `type` decides how it is parsed and rendered. One column beats a
 * sparse table of typed columns that is mostly null whatever anyone configures.
 */
export const customField = pgTable(
  "custom_field",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    boardId: uuid("board_id")
      .notNull()
      .references(() => board.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    type: text("type").$type<"text" | "number" | "date" | "select" | "checkbox">().notNull(),
    /** Choices for a select field; empty for every other type. */
    options: jsonb("options").$type<string[]>().notNull().default([]),
    position: text("position").notNull(),
  },
  (t) => [index("custom_field_board_idx").on(t.boardId, t.position)],
);

export const customFieldValue = pgTable(
  "custom_field_value",
  {
    cardId: uuid("card_id")
      .notNull()
      .references(() => card.id, { onDelete: "cascade" }),
    fieldId: uuid("field_id")
      .notNull()
      .references(() => customField.id, { onDelete: "cascade" }),
    value: text("value").notNull(),
  },
  (t) => [primaryKey({ columns: [t.cardId, t.fieldId] })],
);

export type CustomFieldRow = typeof customField.$inferSelect;


/* ---------------------------------------------------------------- M4 tables */

/**
 * API tokens.
 *
 * Only the hash is stored, so a database dump does not hand over anyone's
 * access — the plaintext is shown once, at creation, and never again.
 */
export const apiToken = pgTable(
  "api_token",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    /** SHA-256 of the token. Indexed because every API call looks it up. */
    tokenHash: text("token_hash").notNull(),
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    createdAt: now(),
  },
  (t) => [
    uniqueIndex("api_token_hash_uq").on(t.tokenHash),
    index("api_token_user_idx").on(t.userId),
  ],
);

/** Outbound webhooks. One row per endpoint per board. */
export const webhook = pgTable(
  "webhook",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    boardId: uuid("board_id")
      .notNull()
      .references(() => board.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    /** Signs the payload so the receiver can prove it came from here. */
    secret: text("secret").notNull(),
    active: boolean("active").notNull().default(true),
    /** Last delivery outcome, so a broken endpoint is visible without logs. */
    lastStatus: integer("last_status"),
    lastError: text("last_error"),
    lastFiredAt: timestamp("last_fired_at", { withTimezone: true }),
    createdAt: now(),
  },
  (t) => [index("webhook_board_idx").on(t.boardId)],
);

/**
 * Automation rules — the Butler equivalent, free and open.
 *
 * Trigger and actions are jsonb because their shape is a discriminated union
 * that will grow; the alternative is a column per action type, mostly null.
 */
export const rule = pgTable(
  "rule",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    boardId: uuid("board_id")
      .notNull()
      .references(() => board.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    enabled: boolean("enabled").notNull().default(true),
    trigger: jsonb("trigger").notNull(),
    actions: jsonb("actions").notNull(),
    /** For the rule list: has this ever actually done anything? */
    lastFiredAt: timestamp("last_fired_at", { withTimezone: true }),
    fireCount: integer("fire_count").notNull().default(0),
    createdAt: now(),
  },
  (t) => [index("rule_board_idx").on(t.boardId)],
);

/** Who wants to hear about a card. Assigning or commenting subscribes you. */
export const watch = pgTable(
  "watch",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    cardId: uuid("card_id")
      .notNull()
      .references(() => card.id, { onDelete: "cascade" }),
    createdAt: now(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.cardId] })],
);

export const notification = pgTable(
  "notification",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    boardId: uuid("board_id")
      .notNull()
      .references(() => board.id, { onDelete: "cascade" }),
    cardId: uuid("card_id").references(() => card.id, { onDelete: "cascade" }),
    kind: text("kind").$type<"mention" | "assigned" | "commented" | "moved" | "due">().notNull(),
    /** Denormalised on purpose: a notification should survive its card. */
    body: text("body").notNull(),
    actorId: text("actor_id").references(() => user.id, { onDelete: "set null" }),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: now(),
  },
  (t) => [index("notification_user_idx").on(t.userId, t.createdAt)],
);

/**
 * Votes.
 *
 * Trello's is a Power-Up; here it is two columns. One vote per person per card,
 * which is what the primary key says and what makes the count meaningful.
 */
export const cardVote = pgTable(
  "card_vote",
  {
    cardId: uuid("card_id")
      .notNull()
      .references(() => card.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    createdAt: now(),
  },
  (t) => [primaryKey({ columns: [t.cardId, t.userId] })],
);

/**
 * Invitations.
 *
 * A fresh self-hosted instance has no mail server, so the link is handed to the
 * admin to pass on however they like. Only the hash is stored, exactly as with
 * API tokens: a database dump must not be a set of working invitations.
 */
export const invite = pgTable(
  "invite",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    email: text("email").notNull(),
    role: text("role").$type<"owner" | "admin" | "member">().notNull().default("member"),
    tokenHash: text("token_hash").notNull(),
    invitedBy: text("invited_by").references(() => user.id, { onDelete: "set null" }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    createdAt: now(),
  },
  (t) => [
    uniqueIndex("invite_token_uq").on(t.tokenHash),
    index("invite_email_idx").on(t.email),
  ],
);

/**
 * Instance settings.
 *
 * Key/value rather than columns, so an owner can change how people get in
 * without an admin editing an env file and restarting the box.
 */
export const setting = pgTable("setting", {
  key: text("key").primaryKey(),
  value: jsonb("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type InviteRow = typeof invite.$inferSelect;

export type ApiTokenRow = typeof apiToken.$inferSelect;
export type WebhookRow = typeof webhook.$inferSelect;
export type RuleRow = typeof rule.$inferSelect;
export type NotificationRow = typeof notification.$inferSelect;
